version: '3.9'

services:
  comments-mongodb:
    image: mongo:6.0
    ports:
      - "127.0.0.24:27017:27017"
    volumes:
      - mongo_data:/data/db

  comments-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.24:3000:3000"
    depends_on:
      - comments-mongodb

  comments-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "127.0.0.24:80:80"

volumes:
  mongo_data: