version: '3.9'

services:
  comments-backend:
    build:
      context: ./commentstest
      dockerfile: Dockerfile
    ports:
      - "127.0.0.24:3000:3000"
    depends_on:
      - mongodb
      - rabbitmq

  captcha-backend:
    build:
      context: ./captcha
      dockerfile: Dockerfile
    depends_on:
      - redis
      - rabbitmq

  comments-frontend:
    image: nginx:latest
    ports:
      - "127.0.0.24:80:80"
    volumes:
      - ./client:/usr/share/nginx/html:ro
    restart: always

  mongodb:
    image: mongo:6.0
    ports:
      - "127.0.0.24:27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "127.0.0.24:6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "127.0.0.24:5672:5672"
      - "127.0.0.24:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  rabbitmq_data:
  redis_data: